name: Mohamed's Auto Commit

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Create file and commit
      run: |
        FILE="commit_number.md"
        if [ ! -f "$FILE" ]; then
          echo "Hello, my name is Mohamed ARI" > "$FILE"
          echo "commit number: 1" >> "$FILE"
        else
          CURRENT_COUNT=$(grep -oP 'commit number: \K\d+' "$FILE")
          if [ -z "$CURRENT_COUNT" ]; then
            CURRENT_COUNT=0
          fi
          NEXT_COUNT=$((CURRENT_COUNT + 1))
          sed -i "/commit number: /c\commit number: $NEXT_COUNT" "$FILE"
        fi
        git config --global user.name "mohamedari1301-cyber"
        git config --global user.email "mohamed.ari1301@gmail.com"
        git add "$FILE"
        git commit -m "Hello, my name is Mohamed ARI nice to meet you"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/beesou777/mean-commit.git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
